### ISSUE TITLE
TwitterLoginStatus always returns error

### ISSUE THREAD

**Issue by Panagiss** [0maru/twitter_login#93]
While I have followed the guide step by step I cannot login on Firebase using Twitter.
Here is my code:
```
Future signInWithTwitter() async {

    // Create a TwitterLogin instance
    final twitterLogin = TwitterLogin(
        apiKey: 'xxxxxxxxx',
        apiSecretKey: 'xxxxxxxxxxxxxxxxxxxx',
        redirectURI: 'my-app://');

    final authResult = await twitterLogin.login();

    switch (authResult.status) {

      case TwitterLoginStatus.loggedIn:
        // success
      print("succ");
        return await FirebaseAuth.instance.signInWithCredential(
          TwitterAuthProvider.credential(
            accessToken: authResult.authToken!,
            secret: authResult.authTokenSecret!,
          ),
        );

        break;

      case TwitterLoginStatus.cancelledByUser:
        // cancel
        print("cancel");
        break;

      case TwitterLoginStatus.error:
        // error
        print("error");
        break;

      default:
        print("def");
        break;
    }
  }
```
AndroidManifest.xml:
```
<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <!-- Accepts URIs that begin with "example://gizmos” -->
                <!-- Registered Callback URLs in TwitterApp -->
                <data android:scheme="my-app" /> <!-- host is option -->
            </intent-filter>
```
And also I have included the updated callback in the Twitter Developer portal: 
![image](https://user-images.githubusercontent.com/56695201/162595752-0322b8c4-7739-4d9f-94c2-2c87bd69d863.png)

Lastly I have set the API key and Secret in the Firebase console and of course I have enabled Twitter sign in.

Twitter_login: ^4.1.0 but I have also tried with 4.0.1

**Comment by 0maru** [comment]
@Panagiss 
I think it works.

There are some things I would like you to go over.
1. authtoken and authTokenSecret is not null or empty?
2. If OAuth1.0a is available on [Twitter Developer portal](https://developer.twitter.com/en/portal/dashboard).
`Projects & Apps > your app > app > User authentication settings > Edit` 
<img src="https://user-images.githubusercontent.com/43493921/162627250-e81a20ed-d81d-40e5-a582-dbc2038e68cb.png" width="80%" />

**Comment by Panagiss** [comment]
Both _authToken_ and _authTokenSecret_ are NULL. 
![image](https://user-images.githubusercontent.com/56695201/162638139-afd676d1-973e-4706-844e-c5f165364e5c.png)
![image](https://user-images.githubusercontent.com/56695201/162638144-b4893a18-413a-4342-9561-ed90b81d97b9.png)

Also yes, I have enabled OAuth 1
![image](https://user-images.githubusercontent.com/56695201/162638171-9eb5a015-124e-4074-84fb-b4d5d2238730.png)

**Comment by shivrajwalkeflutter** [comment]
same error

**Comment by katsuyax** [comment]
I got the same error.

**Comment by katsuyax** [comment]
I made a PR because I fixed it. Can you see it?

**Comment by 0maru** [comment]
@katsuyax @shivrajwalkeflutter @katsuyax 
4.1.1 is now available.
Could you please confirm the correction?

**Comment by katsuyax** [comment]
@0maru 
I confirmed that both API V1 and V2 can login and there is no problem with the status.

**Comment by Panagiss** [comment]
Still getting the same error. I have upgraded to 4.1.1 though. Any thoughts?

**Comment by sandeepunify** [comment]
I/flutter (11990): TwitterLoginStatus.error
I/flutter (11990): null (authResult.authToken)
I/flutter (11990): null (authResult.authTokenSecret)
I/flutter (11990): HttpException: Failed Forbidden

Please solve this problem. i am getting every time this error.

**Comment by sandeepunify** [comment]
@0maru please update on this issue.

**Comment by 0maru** [comment]
@Panagiss @sandeepunify 
Please add callback url of `example://` to Twitter Developer.
Then check if you can loggedIn with the twitter_login example project.

If the sample project works, please share your project with me via git or zip.

**Comment by sandeepunify** [comment]
@0maru 
My twitter app name is ujjain
in AndroidMenifest.xml
<intent-filter>
<action android:name="android.intent.action.VIEW" />

<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />

<data android:scheme="ujjain"
    android:host=""/>

My login code is 
_loginWithTwitter() async {
    final twitterLogin = TwitterLogin(
      // Consumer API keys
      apiKey: 'U0znixSV2xwALteGmglKdiZpY',
      // Consumer API Secret keys
      apiSecretKey: 'nn8lWiOr9DawGkxpbUB3E6DtpO7i1DEiuuZWmJFBYpKSvA9Ex2',
      // Registered Callback URLs in TwitterApp
      // Android is a deeplink
      // iOS is a URLScheme
      redirectURI: 'ujjain://',
    );
    final authResult = await twitterLogin.login();
    print("kakku");
    print(authResult.status);
    print(authResult.authToken);
    print(authResult.authTokenSecret);
    print(authResult.errorMessage);

    // switch (authResult.status) {
    //   case TwitterLoginStatus.loggedIn:
    //     print("dfsffff");
    //     // success
    //     break;
    //   case TwitterLoginStatus.cancelledByUser:
    //     print("555555");
    //     // cancel
    //     break;
    //   case TwitterLoginStatus.error:
    //     // error
    //     print("ERRRRRRR");
    //     break;
    // }
  }

![1](https://user-images.githubusercontent.com/67996880/163666928-b9679d90-90ee-438b-afc1-9907852c3ec3.PNG)
![2](https://user-images.githubusercontent.com/67996880/163666940-40f4052c-4cc6-4056-a466-9ba8d7b58bb6.PNG)

**Comment by 0maru** [comment]
@sandeepunify 
Do not share the API KEY and API SECRET KEY.
I recommend that you regenerate API KEY.

**Comment by sandeepunify** [comment]
@0maru 
![1](https://user-images.githubusercontent.com/67996880/163667171-d9ec542b-a4bb-4780-b4ba-2132452a825b.PNG)
![2](https://user-images.githubusercontent.com/67996880/163667176-e1f3321e-377d-4d2f-b157-75c6de628e53.PNG)

<intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="ujjain"
                    android:host=""/>
            </intent-filter>

**Login Code:** 

_loginWithTwitter() async {
    final twitterLogin = TwitterLogin(
      // Consumer API keys
      apiKey: 'api_key',
      // Consumer API Secret keys
      apiSecretKey: 'api_secret_key',
      // Registered Callback URLs in TwitterApp
      // Android is a deeplink
      // iOS is a URLScheme
      redirectURI: 'ujjain://',
    );
    final authResult = await twitterLogin.login();
    print("kakku");
    print(authResult.status);
    print(authResult.authToken);
    print(authResult.authTokenSecret);
    print(authResult.errorMessage);

    // switch (authResult.status) {
    //   case TwitterLoginStatus.loggedIn:
    //     // success
    //     break;
    //   case TwitterLoginStatus.cancelledByUser:
    //     // cancel
    //     break;
    //   case TwitterLoginStatus.error:
    //     // error
    //     break;
    // }
  }

**twitter_login:  4.2.0**
what should be use **Type of App ?**
My app is hybrid
Thanks

**Comment by 0maru** [comment]
@katsuyax 
The code looks fine.
Can we share a project?

> what should be use Type of App ?
Whichever you choose, it will work fine.
Web App or Native App is recommended.

**Comment by sandeepunify** [comment]
@0maru 
https://github.com/sandeepunify/twitter_login
please check and let me  know what is the issue

**Comment by katsuyax** [comment]
@0maru 
I think the cause is different from other people.

I tried with a native app.
The error I got was that the code returned a string with the ID expecting an int.
This is due to the difference in JSON returned by Twitter between V1 and V2.
So my fix fixed it.

**Comment by 0maru** [comment]
@sandeepunify 
Thanks.

It worked fine.
- Pixel 5a  Android 12
- Emulator Android 9.0 (Google Play)
- Emulator Android 10.0 (Google Play)

If running on an emulator, regenerate the emulator.
If you are using a terminal, reboot it.

**Comment by sandeepunify** [comment]
@0maru 
Thank for your reply
At my side, I don't know why this is not working
every time returning error.
there can be twitter app configuration settings problem?

**Comment by sandeepunify** [comment]
@0maru 
**Problem has fixed now**
after searching your code on github 
I replaced final authResult = await twitterLogin.login() to
final authResult = await twitterLogin.loginV2();
now working fine.
Thanx for support

**Comment by Panagiss** [comment]
@0maru @katsuyax That was the problem for me also. 
When I used ```twitterLogin.loginV2()``` it returned success !! I got another error where it stated that I only have essential access and not elevated access, but that's another thing which is different.

So yeah the fix was to switch to V2 method!

**Comment by Panagiss** [comment]
Here is the full error: 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_auth/invalid-credential] The supplied auth credential is malformed or has expired. [ Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 403, http response: {"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal.
```
I made the application for Elavated privileges, BUT my question why don't you use the V2 API and get rid of the need to applu for Elevated access? 
Am I missing something?

Thanks

**Comment by 0maru** [comment]
@Panagiss 
Twitter API v1.1 is not available when creating a new application in twitter developer from November 15, 2021.
You must apply to be able to use v1 if you need the user's email address.
This is a problem because Twitter does not provide api v1 to all users.
Also, api v2 does not provide a way to retrieve a user's email address.

And flutterfire_ui does not support loginV2.
You must either make flutterfire_ui loginV2 compliant, use twitter_login, or enable api v1.
